### ISSUE TITLE
Questions about the complete source codes and mutation codes in DUT

### ISSUE THREAD

**Issue by zhangkanqi** [sycuricon/MorFuzz#3]
Hi, I have some questions about morfuzz.

(1) I find that you have offered the co-sim framwork(riscv-isa-cosim) , the template generator(razzle) and morfuzz_bin, I think it's a little scattered. So I wonder have you ever open-sourced the complete running codes of morfuzz? 

(2) Besides, to my knowledge, I argue that razzle generates instruction objects, and these objects are instantiated and mutated in riscv-isa-cosim(i.e. spike).  Is my opinion correct? I didn't find mutation codes in DUT such as BOOM.

Looking forward to your reply.

**Comment by Phantom1003** [comment]
Hi. During the artifact evaluation, we participated in the HACK@DAC competition, and as a result, we released MorFuzz as pre-built binaries. To compile the `morfuzz_bin/cj`, you can execute `make install` under the `riscv-isa-cosim` repository. And the `morfuzz_bin/razzle` is packaged from `razzle`. Currently, our top repository is experiencing configuration issues due to the limitations of the poor build tool. We plan to re-organize it in the future.

Regarding the second question, the answer is yes.
